const {test}=require('node:test');
const assert=require('node:assert/strict');
const {mkdtempSync,rmSync}=require('node:fs');
const {tmpdir}=require('node:os');
const path=require('node:path');
const {createStore}=require('../store.cjs');
const {createWorkflow}=require('../workflow.cjs');
function input(version='v1',when='2026-09-09T01:00:00Z') {return {companyId:'company-test',deadline:'2026-12-01T10:00:00+08:00',handoff:{schemaVersion:'1.0',task:{taskId:'task-test',title:'测试项目'},snapshot:{documentVersion:version,reportId:'report-'+version,checksum:'a'.repeat(64),generatedAt:when,completeness:1,confidence:0.98},latestDocumentVersion:version,superseded:false,status:'ready',requirements:[],warnings:[],evidence:[]},rules:[]};}
function setup(t){const dir=mkdtempSync(path.join(tmpdir(),'bid-flow-'));const file=path.join(dir,'flow.db');const store=createStore(file);t.after(()=>{try{store.close();}catch{}rmSync(dir,{recursive:true,force:true});});const workflow=createWorkflow({store,assess:()=>({decision:'follow',items:[],blockers:[],actions:[]}),clock:()=>Date.parse('2026-09-09T02:00:00Z'),chatId:'chat-test',operatorIds:['actor-test']});return{dir,file,store,workflow};}
test('duplicate snapshots create one project and outbox, survive restart',t=>{const {store,workflow,file}=setup(t);const a=workflow.ingest(input());const b=workflow.ingest(input());assert.equal(a.id,b.id);assert.equal(store.listOutbox(0).length,1);store.close();const again=createStore(file);assert.equal(again.getProject(a.id).version,'v1');again.close();});
test('same version content conflict and stale previous version cannot replace current',t=>{const {workflow}=setup(t);const a=workflow.ingest(input());const conflict=input();conflict.handoff.snapshot.checksum='b'.repeat(64);assert.throws(()=>workflow.ingest(conflict),/version_conflict/);workflow.ingest(input('v2','2026-09-09T01:30:00Z'));assert.throws(()=>workflow.act({projectId:a.id,version:'v1',action:'follow',actorId:'actor-test',chatId:'chat-test',eventId:'e1'}),/stale/);assert.throws(()=>workflow.ingest(input('v0','2026-09-08T01:00:00Z')),/stale/);});
test('writing needs authorized current card, follow decision and ready snapshot; duplicates reuse job',t=>{const {workflow,store}=setup(t);const p=workflow.ingest(input());const base={projectId:p.id,version:p.version,cardKey:store.key(p.input,p.assessment),actorId:'actor-test',chatId:'chat-test',messageId:'msg-test'};store.bindMessage(p.id,'msg-test');assert.throws(()=>workflow.act({...base,eventId:'bad',action:'follow',actorId:'stranger'}),/not_allowed/);assert.throws(()=>workflow.act({...base,eventId:'early',action:'write'}),/follow_required/);workflow.act({...base,eventId:'follow',action:'follow'});const a=workflow.act({...base,eventId:'write-1',action:'write'});const b=workflow.act({...base,eventId:'write-2',action:'write'});assert.equal(a.writingJobId,b.writingJobId);assert.equal(store.listWriting().length,1);assert.throws(()=>workflow.act({...base,eventId:'wrong-message',messageId:'other',action:'defer'}),/message_mismatch/);});
test('unknown deadline and manual blocking cannot generate even when followed',t=>{const {workflow,store}=setup(t);const i=input();i.deadline='';i.handoff.status='needs_manual';const p=workflow.ingest(i);store.bindMessage(p.id,'m');const base={projectId:p.id,version:p.version,cardKey:store.key(p.input,p.assessment),actorId:'actor-test',chatId:'chat-test',messageId:'m'};workflow.act({...base,eventId:'f',action:'follow'});assert.throws(()=>workflow.act({...base,eventId:'w',action:'write'}),/not_ready/);});
test('new document keeps message binding but clears human decision',t=>{const {workflow,store}=setup(t);const p=workflow.ingest(input());store.bindMessage(p.id,'m');workflow.act({projectId:p.id,version:p.version,cardKey:store.key(p.input,p.assessment),action:'follow',actorId:'actor-test',chatId:'chat-test',messageId:'m',eventId:'f'});const v2=workflow.ingest(input('v2','2026-09-09T01:30:00Z'));assert.equal(v2.messageId,'m');assert.equal(v2.humanDecision,null);assert.equal(store.getProject(p.id).current,false);});
module.exports={input};
test('same snapshot safety downgrade refreshes input and revokes writing',t=>{const {workflow,store}=setup(t);const p=workflow.ingest(input());store.bindMessage(p.id,'m');const base={projectId:p.id,version:p.version,cardKey:store.key(p.input,p.assessment),actorId:'actor-test',chatId:'chat-test',messageId:'m'};workflow.act({...base,eventId:'f',action:'follow'});workflow.act({...base,eventId:'w',action:'write'});const changed=input();changed.handoff.warnings=[{code:'manual',blocked:true}];workflow.ingest(changed);assert.equal(store.getProject(p.id).humanDecision,null);assert.equal(store.getProject(p.id).input.handoff.warnings.length,1);assert.equal(store.listWriting()[0].status,'cancelled');});
test('writing confirmation requires current challenge and explicit placeholder approval',t=>{const {workflow,store}=setup(t);const p=workflow.ingest(input());store.bindMessage(p.id,'m');const base={projectId:p.id,version:p.version,cardKey:store.key(p.input,p.assessment),actorId:'actor-test',chatId:'chat-test',messageId:'m'};workflow.act({...base,eventId:'f',action:'follow'});workflow.act({...base,eventId:'w',action:'write'});const job=store.listWriting()[0];store.updateWriting(job.id,'waiting_confirmation',{confirmation:{type:'global_facts',challenge:'fresh',groups:[{id:'g',fields:[]}]}},0,'content');assert.throws(()=>workflow.act({...base,eventId:'c1',action:'continue',challenge:'old'}),/confirmation/);store.set('previewDelivered:fresh','preview-message');workflow.act({...base,eventId:'c2',action:'continue',challenge:'fresh'});assert.equal(store.listWriting()[0].payload.confirmations.globalFacts.challenge,'fresh');assert.equal(store.listWriting()[0].status,'queued');});
