'use strict';
const fs = require('node:fs');
const path = require('node:path');
const cp = require('node:child_process');
const { createHash } = require('node:crypto');
const [consumerRoot, providerPromptPath] = process.argv.slice(2);
if (!consumerRoot || !providerPromptPath) throw new Error('Usage: node export-patches.cjs <consumer-worktree> <provider-prompts.ts>');
const git = args => cp.execFileSync('git', args, { cwd: consumerRoot, encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 });
let consumer = git(['diff', '--binary', 'HEAD', '--', 'server', 'shared']);
const testFile = 'server/modules/preread/preread-codex-compat.spec.ts';
const testLines = fs.readFileSync(path.join(consumerRoot, testFile), 'utf8').replace(/\r\n/g, '\n').trimEnd().split('\n');
consumer += `diff --git a/${testFile} b/${testFile}\nnew file mode 100644\n--- /dev/null\n+++ b/${testFile}\n@@ -0,0 +1,${testLines.length} @@\n` + testLines.map(line => '+' + line).join('\n') + '\n';
fs.writeFileSync(path.join(__dirname, 'consumer.patch'), consumer);
const original = fs.readFileSync(providerPromptPath, 'utf8').replace(/\r\n/g, '\n');
const note = '\n\n结构化字段仅填写原文明示的信息。page只填写已确认的正整数单页码；多页、范围或未知页码不填page，把原始定位逐字保留在section，confidence不超过0.79。所有未知boolean、分类、阈值、期限、分数和权重均省略，不以false或0代替未知。资格条件可包含qualification:{category:company|certificate|license|performance|project_manager|technical_lead|personnel|finance_tax_social_credit|consortium_subcontract|other,mandatory:boolean,minimumRequirement:string,evidenceRequirement:string,supplementableBeforeDeadline:boolean}；商务条款可包含commercial:{materialCategory:company|certificate|personnel|performance|manufacturer|service|submission|other,responsibleRole:商务负责人|项目负责人|财务|法务|厂商接口人|投标文件编制人,consequence:string,supplementableBeforeDeadline:boolean}；废标风险可包含redline:{category:qualification|substantive|invalid_bid,triggerCondition:string,consequence:string,supplementableBeforeDeadline:boolean}；评分项可包含evaluation:{category:technical|commercial|price,reviewFocus:string,maximumScore:number,weightPercent:number,earningCondition:string,evidenceRequirement:string,investmentPriority:high|medium|low}。不能将主观分/客观分推断为技术/商务；无法分类时保留原分类供人工核实。描述字段保留原文，不推断投标人是否满足或能否补齐。';
const revised = original.replace('禁止解释、Markdown、注释和省略号。`;', '禁止解释、Markdown、注释和省略号。' + note + '`;').replace('所有数组合计最多 36 条，评分项最多 32 条。', 'page只填写已确认的正整数单页码；多页、范围或未知时省略page并将原始定位保留在section，confidence不超过0.79。category仅在原文明示技术、商务、价格时分别填写technical、commercial、price；主观/客观等其他分类保留原分类供人工核实，禁止猜测。未知字段省略，不用false、0或任意分类替代。\n\n所有数组合计最多 36 条，评分项最多 32 条。');
const oldLines = original.trimEnd().split('\n'), newLines = revised.trimEnd().split('\n');
const provider = 'diff --git a/src/model-provider/prompts.ts b/src/model-provider/prompts.ts\n--- a/src/model-provider/prompts.ts\n+++ b/src/model-provider/prompts.ts\n' + `@@ -1,${oldLines.length} +1,${newLines.length} @@\n` + oldLines.map(line => '-' + line).join('\n') + '\n' + newLines.map(line => '+' + line).join('\n') + '\n';
fs.writeFileSync(path.join(__dirname, 'provider-prompt.future.patch'), provider);
const digest = content => createHash('sha256').update(content).digest('hex');
fs.writeFileSync(path.join(__dirname, 'manifest.json'), JSON.stringify({ consumerBaseCommit: git(['rev-parse', 'HEAD']).trim(), consumerPatchSha256: digest(consumer), providerOriginalNormalizedSha256: digest(original), providerPatchSha256: digest(provider), providerPromptPatchDeployed: false }, null, 2) + '\n');
console.log('Exported consumer.patch, provider-prompt.future.patch, manifest.json');
